# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIntValidator

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(824, 722)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 676))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(222, 218, 210);")
        self.tabWidget.setObjectName("tabWidget")
        self.generadorTab = QtWidgets.QWidget()
        self.generadorTab.setObjectName("generadorTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.generadorTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.generadorTab)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.modValuesLabel = QtWidgets.QLabel(self.layoutWidget)
        self.modValuesLabel.setObjectName("modValuesLabel")
        self.verticalLayout_7.addWidget(self.modValuesLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.modValuesCheckBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.modValuesCheckBox.setText("")
        self.modValuesCheckBox.setChecked(False)
        self.modValuesCheckBox.setObjectName("modValuesCheckBox")
        self.horizontalLayout_2.addWidget(self.modValuesCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.semillaLabel = QtWidgets.QLabel(self.layoutWidget)
        self.semillaLabel.setObjectName("semillaLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.semillaLabel)
        self.semillaLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        #Validar ingreso de int
        self.semillaLineEdit.setValidator(QIntValidator())
        self.semillaLineEdit.setEnabled(True)
        self.semillaLineEdit.setObjectName("semillaLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.semillaLineEdit)
        self.aLabel = QtWidgets.QLabel(self.layoutWidget)
        self.aLabel.setObjectName("aLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.aLabel)
        self.aLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        #Validar ingreso de int
        self.aLineEdit.setValidator(QIntValidator())
        self.aLineEdit.setPlaceholderText("")
        self.aLineEdit.setObjectName("aLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.aLineEdit)
        self.cLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cLabel.setObjectName("cLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.cLabel)
        self.cLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        #Validar ingreso de int
        self.cLineEdit.setValidator(QIntValidator())
        self.cLineEdit.setEnabled(True)
        self.cLineEdit.setPlaceholderText("")
        self.cLineEdit.setObjectName("cLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cLineEdit)
        self.mLabel = QtWidgets.QLabel(self.layoutWidget)
        self.mLabel.setObjectName("mLabel")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mLabel)
        self.mLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        #Validar ingreso de int
        self.mLineEdit.setValidator(QIntValidator())
        self.mLineEdit.setEnabled(True)
        self.mLineEdit.setPlaceholderText("")
        self.mLineEdit.setObjectName("mLineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mLineEdit)
        self.tipoGenLabel = QtWidgets.QLabel(self.layoutWidget)
        self.tipoGenLabel.setObjectName("tipoGenLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.tipoGenLabel)
        self.tipoGenComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.tipoGenComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.tipoGenComboBox.setObjectName("tipoGenComboBox")
        self.tipoGenComboBox.addItem("")
        self.tipoGenComboBox.addItem("")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tipoGenComboBox)
        self.cantSubintervLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cantSubintervLabel.setObjectName("cantSubintervLabel")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.cantSubintervLabel)
        self.cantSubintervComboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cantSubintervComboBox.sizePolicy().hasHeightForWidth())
        self.cantSubintervComboBox.setSizePolicy(sizePolicy)
        self.cantSubintervComboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.cantSubintervComboBox.setObjectName("cantSubintervComboBox")
        self.cantSubintervComboBox.addItem("")
        self.cantSubintervComboBox.addItem("")
        self.cantSubintervComboBox.addItem("")
        self.cantSubintervComboBox.addItem("")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cantSubintervComboBox)
        self.verticalLayout_7.addLayout(self.formLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem2)
        self.cantLabel = QtWidgets.QLabel(self.layoutWidget)
        self.cantLabel.setObjectName("cantLabel")
        self.verticalLayout_7.addWidget(self.cantLabel)
        self.cantLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        #Validar ingreso de int
        self.cantLineEdit.setValidator(QIntValidator())
        self.cantLineEdit.setObjectName("cantLineEdit")
        self.verticalLayout_7.addWidget(self.cantLineEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.generatePushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.generatePushButton.setObjectName("generatePushButton")
        self.horizontalLayout_4.addWidget(self.generatePushButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.limpiarPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limpiarPushButton.sizePolicy().hasHeightForWidth())
        self.limpiarPushButton.setSizePolicy(sizePolicy)
        self.limpiarPushButton.setObjectName("limpiarPushButton")
        self.horizontalLayout_4.addWidget(self.limpiarPushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.histogramaPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.histogramaPushButton.setObjectName("histogramaPushButton")
        self.horizontalLayout_5.addWidget(self.histogramaPushButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.varpLabel = QtWidgets.QLabel(self.layoutWidget)
        self.varpLabel.setObjectName("varpLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.varpLabel)
        self.varpLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.varpLineEdit.sizePolicy().hasHeightForWidth())
        self.varpLineEdit.setSizePolicy(sizePolicy)
        self.varpLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.varpLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.varpLineEdit.setObjectName("varpLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.varpLineEdit)
        self.mediaLabel = QtWidgets.QLabel(self.layoutWidget)
        self.mediaLabel.setObjectName("mediaLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mediaLabel)
        self.mediaLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mediaLineEdit.sizePolicy().hasHeightForWidth())
        self.mediaLineEdit.setSizePolicy(sizePolicy)
        self.mediaLineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.mediaLineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.mediaLineEdit.setObjectName("mediaLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mediaLineEdit)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.calcPushButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calcPushButton.sizePolicy().hasHeightForWidth())
        self.calcPushButton.setSizePolicy(sizePolicy)
        self.calcPushButton.setObjectName("calcPushButton")
        self.horizontalLayout_8.addWidget(self.calcPushButton)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dataTableWidget = QtWidgets.QTableWidget(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTableWidget.sizePolicy().hasHeightForWidth())
        self.dataTableWidget.setSizePolicy(sizePolicy)
        self.dataTableWidget.setMinimumSize(QtCore.QSize(0, 450))
        self.dataTableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(1)
        self.dataTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.dataTableWidget.setHorizontalHeaderItem(0, item)
        self.verticalLayout_6.addWidget(self.dataTableWidget)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem12)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.horizontalLayout_6.addWidget(self.splitter)
        self.tabWidget.addTab(self.generadorTab, "")
        
        self.chiTab = QtWidgets.QWidget()
        self.chiTab.setObjectName("chiTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.chiTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chiTableWidget = QtWidgets.QTableWidget(self.chiTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chiTableWidget.sizePolicy().hasHeightForWidth())
        self.chiTableWidget.setSizePolicy(sizePolicy)
        self.chiTableWidget.setMinimumSize(QtCore.QSize(0, 450))
        self.chiTableWidget.setWordWrap(True)
        self.chiTableWidget.setObjectName("chiTableWidget")
        self.chiTableWidget.setColumnCount(6)
        self.chiTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chiTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chiTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chiTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chiTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chiTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.chiTableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_8.addWidget(self.chiTableWidget)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.chiTab)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sumaChiLineEdit = QtWidgets.QLineEdit(self.chiTab)
        self.sumaChiLineEdit.setObjectName("sumaChiLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sumaChiLineEdit)
        self.label_2 = QtWidgets.QLabel(self.chiTab)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.chiTabuladoLineEdit = QtWidgets.QLineEdit(self.chiTab)
        self.chiTabuladoLineEdit.setObjectName("chiTabuladoLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.chiTabuladoLineEdit)
        self.verticalLayout_3.addLayout(self.formLayout_3)
        self.resultadoLineEdit = QtWidgets.QLineEdit(self.chiTab)
        self.resultadoLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.resultadoLineEdit.setObjectName("resultadoLineEdit")
        self.verticalLayout_3.addWidget(self.resultadoLineEdit)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_12.addLayout(self.verticalLayout_3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem15)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.tabWidget.addTab(self.chiTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.modValuesCheckBox, self.semillaLineEdit)
        MainWindow.setTabOrder(self.semillaLineEdit, self.aLineEdit)
        MainWindow.setTabOrder(self.aLineEdit, self.cLineEdit)
        MainWindow.setTabOrder(self.cLineEdit, self.mLineEdit)
        MainWindow.setTabOrder(self.mLineEdit, self.tipoGenComboBox)
        MainWindow.setTabOrder(self.tipoGenComboBox, self.generatePushButton)
        MainWindow.setTabOrder(self.generatePushButton, self.histogramaPushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.modValuesLabel.setText(_translate("MainWindow", "Modificar valores:"))
        self.semillaLabel.setText(_translate("MainWindow", "Semilla:"))
        self.semillaLineEdit.setText(_translate("MainWindow", "141"))
        self.semillaLineEdit.setPlaceholderText(_translate("MainWindow", "141"))
        self.aLabel.setText(_translate("MainWindow", "a:"))
        self.aLineEdit.setText(_translate("MainWindow", "15005"))
        self.cLabel.setText(_translate("MainWindow", "C:"))
        self.cLineEdit.setText(_translate("MainWindow", "8371"))
        self.mLabel.setText(_translate("MainWindow", "m:"))
        self.mLineEdit.setText(_translate("MainWindow", "19993"))
        self.tipoGenLabel.setText(_translate("MainWindow", "Generador:"))
        self.tipoGenComboBox.setItemText(0, _translate("MainWindow", "Congruente Mixto"))
        self.tipoGenComboBox.setItemText(1, _translate("MainWindow", "Congruente Multiplicativo"))
        self.cantSubintervLabel.setText(_translate("MainWindow", "Cantidad Subintervalos"))
        self.cantSubintervComboBox.setItemText(0, _translate("MainWindow", "5"))
        self.cantSubintervComboBox.setItemText(1, _translate("MainWindow", "8"))
        self.cantSubintervComboBox.setItemText(2, _translate("MainWindow", "10"))
        self.cantSubintervComboBox.setItemText(3, _translate("MainWindow", "12"))
        self.cantLabel.setText(_translate("MainWindow", "Cantidad números a generar:"))
        self.generatePushButton.setText(_translate("MainWindow", "Generar"))
        self.limpiarPushButton.setText(_translate("MainWindow", "Limpiar Datos"))
        self.histogramaPushButton.setText(_translate("MainWindow", "Generar histograma"))
        self.label_3.setText(_translate("MainWindow", "Unidades de Resumen:"))
        self.varpLabel.setText(_translate("MainWindow", "Varianza:"))
        self.mediaLabel.setText(_translate("MainWindow", "Media:"))
        self.calcPushButton.setText(_translate("MainWindow", "Calcular"))
        item = self.dataTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Números Generados"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generadorTab), _translate("MainWindow", "Generador"))
        #self.tabWidget.setTabText(self.tabWidget.indexOf(self.graficoTab), _translate("MainWindow", "Histograma"))
        item = self.chiTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Intervalos"))
        item = self.chiTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Frec. Obtenida"))
        item = self.chiTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Frec. Esperada"))
        item = self.chiTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "(fo-fe)^2"))
        item = self.chiTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "(col3)/fe"))
        item = self.chiTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sumatoria"))
        self.label.setText(_translate("MainWindow", "Sumatoria de Chi Cuadrado:"))
        self.label_2.setText(_translate("MainWindow", "Chi Tabulado:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.chiTab), _translate("MainWindow", "Chi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

